### ISSUE TITLE
CSS 布局的一些

### ISSUE THREAD

**Issue by fefz** [fefz/miscellaneous#1]
- `box-sizing` 属性有常用的俩个值
  - `content-box`：  `width`和`height`包含`padding`和`border`的值，等同于标准盒子模型
  - `padding-box`： `width`和`height`包含`padding`的值
  - `border-box`：  `width`和`height`不包含`padding`和`border`的值 

  -  ![image](https://user-images.githubusercontent.com/16323430/27170435-718eeca2-51e0-11e7-9316-4e05d310ec5b.png)

---

- 使用`flex`实现垂直居中布局
  ```css
  .vertical-container {
    height: 200px;
    display: flex;
    display: -webkit-flex;
    align-items: center; // 垂直居中
    -webkit-align-items: center;
    justify-content: center; // 水平居中
    -webkit-justify-content: center;
  }
  ```

---
